languageCode = "fi"
title = "paint.net suomeksi"
DefaultContentLanguage = "fi"
disableKinds = [ "RSS", "tags", "categories", "taxonomy", "taxonomyTerm", "section", "404" ]
enableRobotsTXT = true
summaryLength = 10
googleAnalytics = "UA-158488951-1"

[menu]

	[[menu.pdn]]
		name = "paint.net ohje"
		identifier = "koti"
		weight = 100

	[[menu.pdn]]
		name = "Käyttöliittymä"
		identifier = "kliittyma"
		weight = 200

	[[menu.pdn]]
		name = "Valikkopalkki"
		identifier = "vpalkki"
		weight = 300

	[[menu.pdn]]
		name = "Säädöt ja tehosteet"
		identifier = "sehot"
		weight = 400

	[[menu.pdn]]
		name = "Työkaluikkuna"
		identifier = "tikkuna"
		weight = 500

	[[menu.pdn]]
		name = "Muuta"
		identifier = "muuta"
		weight = 600

[module]

	[[module.mounts]]
		source = "content"
		target = "content"

	[[module.mounts]]
		source = "static"
		target = "static"

	[[module.mounts]]
		source = "layouts"
		target = "layouts"

	[[module.mounts]]
		source = "data"
		target = "data"

	[[module.mounts]]
		source = "assets"
		target = "assets"

	[[module.mounts]]
		source = "archetypes"
		target = "archetypes"

	[[module.mounts]]
		source = "node_modules/@vizuaalog/bulmajs/dist/"
		target = "static/bulmajs/"