baseurl = "https://paintdotnet.arkku.net/"
languageCode = "fi"
title = "paint.net suomeksi"
DefaultContentLanguage = "fi"
disableKinds = [ "RSS", "tags", "categories", "taxonomy", "taxonomyTerm" ]
enableGitInfo = true
enableRobotsTXT = true
summaryLength = 10

[[menu.pdn]]
	name = "paint.net ohje"
	identifier = "koti"
	weight = 100

[[menu.pdn]]
	name = "Käyttöliittymä"
	identifier = "kliittyma"
	weight = 200

[[menu.pdn]]
	name = "Valikkopalkki"
	identifier = "vpalkki"
	weight = 300

[[menu.pdn]]
	name = "Säädöt ja tehosteet"
	identifier = "sehot"
	weight = 400

[[menu.pdn]]
	name = "Työkaluikkuna"
	identifier = "tikkuna"
	weight = 500

[[menu.pdn]]
	name = "Muuta"
	identifier = "muuta"
	weight = 600	
