[build]
    publish = "public"

[context.production]
    command = "hugo --gc --minify -b $URL"
    environment = { HUGO_ENABLEGITINFO = "true", HUGO_VERSION = "0.78.1" }

[context.deploy-preview]
    command = "hugo --minify -b $DEPLOY_PRIME_URL"
    environment = { HUGO_VERSION = "0.78.1" }

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Referrer-Policy = "no-referrer"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "default-src 'self' https://www.googletagmanager.com;"